### ISSUE TITLE
graphql_ppx setup?

### ISSUE THREAD

**Issue by idkjs** [drejohnson/reason-react-razzle#1]
Good afternoon, sir. What is your reason/opam set up, if you dont mind sharing? Did you use [recommend](https://reasonml.github.io/docs/en/global-installation.html#recommended-through-npm-yarn) or [alternative](https://reasonml.github.io/docs/en/global-installation.html#alternative-through-opam) setup? Seems you cant get graphql_ppx and not screw up your editor if you use the standard setup. @jordwalke @mhallin

**Comment by drejohnson** [comment]
I use the recommended setup for Reason. For opam, I installed the binary dist for Linux from https://opam.ocaml.org/doc/Install.html. No editor issues for me.

**Comment by idkjs** [comment]
ok. thanks.
